### ISSUE TITLE
API 3

### ISSUE THREAD

**Issue by NML32** [applqpak/TimeBan#1]
Could you add api version 3.0.0-ALPHA1 to plugin.yml? 
The latest build #61 of pmmp/PocketMine-MP (mcpe-1.0)  is looking for api  3.0.0.-ALPHA1

**Comment by applqpak** [comment]
done!

**Comment by applqpak** [comment]
[![Poggit-CI](https://poggit.pmmp.io/ci.badge/applqpak/TimeBan/TimeBan)](https://poggit.pmmp.io/ci/applqpak/TimeBan/TimeBan)
[TimeBan.phar](https://poggit.pmmp.io/r/427/TimeBan.phar)
